<?xml version="1.0"?>

<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="wheel_offset_x" value="0.0"/>
  <xacro:property name="wheel_offset_y" value="0.0"/>
  <xacro:property name="wheel_offset_z" value="0.0"/>

  <xacro:property name="wheel_mass" value="0.1"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.01"/>

  <xacro:property name="body_height" value="0.1"/>
  <xacro:property name="body_width" value="0.45"/>
  <xacro:property name="body_length" value="0.4"/>
  <xacro:property name="mass" value="5.0"/>

  <xacro:property name="wheeltrack" value="0.5"/>
  <xacro:property name="wheelbase" value="0.3"/>
  
  <xacro:property name="chassis_offset_z" value="0.0"/>
  <xacro:property name="chassis_offset_y" value="0.0"/>
  <xacro:property name="chassis_offset_x" value="0.0"/>

  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/imu.urdf.xacro" />

  <material name="white">
      <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
      <color rgba="1 0 0 1"/>
  </material>

  <link name="base_link">
  </link>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body_link"/>
    <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${-wheel_offset_z}" rpy ="0 0 ${pi/2}"/>
  </joint>
    
  <link name="body_link">
    <visual>
        <geometry>
          <mesh filename="file://$(find robot_description)/urdf/shorty_pizza.stl" scale="0.005 0.005 0.005"/>
        </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia ixx="${(1/12) * mass * (body_width*body_width+body_height*body_height)}" ixy="0.0" ixz="0.0"
               iyy="${(1/12) * mass * (body_length*body_length+body_height*body_height)}" iyz="0.0"
               izz="${(1/12) * mass * (body_length*body_length+body_width*body_width)}"/>
    </inertial>
  </link>

  <gazebo reference="body_link">
    <material>Gazebo/Orange</material>
  </gazebo>


  <xacro:macro name="wheel" params="prefix">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}" />
        <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" iyz="0.0"
                 izz="${(1/12) * wheel_mass * (wheel_radius*wheel_radius)}"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left"/>
  <xacro:wheel prefix="front_right"/>
  <xacro:wheel prefix="rear_left"/>
  <xacro:wheel prefix="rear_right"/>


  <xacro:macro name="wheel_joint" params="prefix origin_xyz">
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${origin_xyz}"/>
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel_joint prefix="front_left" origin_xyz="${wheelbase / 2 + chassis_offset_x} ${wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="front_right" origin_xyz="${wheelbase / 2 + chassis_offset_x} ${-wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="rear_left" origin_xyz="${-wheelbase / 2 + chassis_offset_x} ${wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="rear_right" origin_xyz="${-wheelbase / 2 + chassis_offset_x} ${-wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>


</robot>
